import { defineCollection, z } from 'astro:content';
import { file } from 'astro/loaders';
import { parse } from 'yaml';

/**
 * Publication types, in the order they are rendered on /publications.
 */
export const PUB_TYPES = [
  'journal',
  'chapter',
  'thesis',
  'report',
  'conference',
  'poster',
] as const;

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 70);

const publications = defineCollection({
  loader: file('src/data/publications.yml', {
    parser: (text) => {
      const parsed = parse(text);
      if (!Array.isArray(parsed)) {
        throw new Error('publications.yml must contain a top-level list of entries.');
      }
      // A DOI is the natural stable id. Entries without one (reports, posters,
      // older conference papers) fall back to a title slug plus year, with a
      // numeric suffix if that still collides — two of the Sandia reports have
      // titles identical up to the slug length limit, and a duplicate id would
      // silently drop one of them.
      const seen = new Map<string, number>();
      return parsed.map((entry, i) => {
        let id: string = entry?.doi ?? `${slugify(entry?.title ?? '')}-${entry?.year ?? i}`;
        const count = seen.get(id) ?? 0;
        seen.set(id, count + 1);
        if (count > 0) id = `${id}-${count + 1}`;
        return { id, ...entry };
      });
    },
  }),
  schema: z.object({
    type: z.enum(PUB_TYPES),
    title: z.string().min(1),
    authors: z.array(z.string().min(1)).min(1),
    year: z.number().int().min(1990).max(2100),

    /** Journal, book series, or conference name. */
    venue: z.string().optional(),
    volume: z.union([z.string(), z.number()]).optional(),
    issue: z.union([z.string(), z.number()]).optional(),
    pages: z.string().optional(),
    /** Article number, for journals that use them instead of page ranges. */
    article: z.union([z.string(), z.number()]).optional(),

    doi: z.string().regex(/^10\.\d{4,9}\//, 'Must be a bare DOI, e.g. 10.1029/2019SW002329').optional(),
    /** Used only when there is no DOI to link to. */
    url: z.string().url().optional(),

    /** Book title, for chapters. */
    book: z.string().optional(),
    /** Institution, for theses and reports. */
    institution: z.string().optional(),
    /** Report/document number, e.g. SAND2010-2547. */
    number: z.string().optional(),
    /** Meeting name and location, for conference papers and posters. */
    meeting: z.string().optional(),

    /** Extra links shown beneath an entry. */
    links: z
      .array(z.object({ label: z.string(), href: z.string().url() }))
      .optional(),

    /**
     * Rank on the home page's selected-work list. Lower sorts first. Omit for
     * everything that is not featured.
     */
    featured: z.number().int().min(1).max(99).optional(),
    /** Why this one matters. Required whenever `featured` is set. */
    impact: z.string().min(1).optional(),

    /**
     * Citation count. Refreshed automatically from OpenAlex by
     * scripts/update_citations.py — do not edit by hand.
     */
    citations: z.number().int().nonnegative().optional(),
    citations_updated: z.string().optional(),
  })
    // A featured entry with no explanation would render an empty card, so make
    // the pair inseparable rather than discovering it in the browser.
    .refine((p) => p.featured === undefined || !!p.impact, {
      message: 'A featured publication must also set `impact` explaining why it is featured.',
      path: ['impact'],
    }),
});

const softwareItem = z.object({
  name: z.string(),
  href: z.string().url(),
  body: z.string(),
  role: z.string().optional(),
  tags: z.array(z.string()).optional(),

  /**
   * Zenodo *concept* DOI — always resolves to the latest release, and is the
   * DOI people should cite. Set by hand; omit for packages with no archive.
   */
  zenodo_concept_doi: z.string().regex(/^10\.5281\/zenodo\.\d+$/).optional(),

  /** Generated by scripts/update_zenodo.py — do not edit by hand. */
  version: z.union([z.string(), z.number()]).optional(),
  version_doi: z.string().optional(),
  released: z.string().optional(),
});

const software = defineCollection({
  loader: file('src/data/software.yml', {
    parser: (text) => {
      const parsed = parse(text) ?? {};
      // The file is grouped by section; flatten to one entry per section so the
      // page can render them in order while the schema still validates items.
      return Object.entries(parsed).map(([section, items]) => ({
        id: section,
        section,
        items,
      }));
    },
  }),
  schema: z.object({
    section: z.enum(['maintained', 'authored', 'reproducible']),
    items: z.array(softwareItem).min(1),
  }),
});

export const collections = { publications, software };
